export interface ICustomerInformationApiResponse {
  customer: {
    custCode: number;
    custTypePsonCode: string;
    custResnAbroadInd: string;
    custCustName: string;
    custSummrCustName: string;
    custStatRegCode: number;
    custTaxNature: string;
    custTradingProfile: string;
    custPsonLinkInd: string;
    custFatcaUsPersonInd: string;
    custFatcaIrsProfileCode: string;
    custFatcaCrsProfileCode: string;
    custFatcaGiinCode: string;
    custFatcaLeiCode: string;
    custFatcaRelatedCountry: string;
    custFatcaRelatedCountryName: string;
    custDepOwnAccNumber: string;
    custDepIndividDepositAcc: number;
    custDepSelicAcc: string;
    custInsertDate: string;
    custUpdateDate: string;
  };
  individualCustomer: {
    indCustBirthDate: string;
    indCustCountryAcrn: string;
    indCustCountryName: string;
    indCustStateAcrn: string;
    indCustStateName: string;
    indCustNameCityBirth: string;
    indCustCountryResAcrn: string;
    indCustCountryResName: string;
    indCustGenderCode: number;
    indCustGenderDscn: string;
    indCustEducationCode: number;
    indCustEducationDscn: string;
    indCustPepInd: string;
    indCustFatherName: string;
    indCustMotherName: string;
    indCustHiredBy: string;
    indCustCompanyDocm: string;
    indCustCompanyName: string;
    indCustJobName: string;
    indCustEconomicActvCode: string;
    indCustEconomicActvName: string;
    indCustLastUpdateDate: string;
    indCustOrdersByThirdParties: string;
    indCustManagedPortfolioAdmin: string;
    indCustInvestmentFundManager: string;
    indCustRiskClassificationInd: number;
    indCustRiskClassificationDscn: string;
    indCustPrivateBankInd: string;
    indCustMaritalCode: number;
    indCustMaritalDescription: string;
    indCustSpouseDocmValue: string;
    indCustSpouseName: string;
    indCustMinorEmancipatedInd: string;
    indCustMinorResponsibleDocm: string;
    indCustMinorResponsibleName: string;
    indCustDeceasedInd: string;
    indCustDeceasedInventoryDocm: string;
    indCustDeceasedInventoryName: string;
  };
  individualCustomerAbroad: {
    indCustAbroadDocmValue: string | null;
    indCustAbroadPrivateBankInd: string;
    indCustAbroadAccOwnershipType: string | null;
    indCustAbroadTaxpayerIdInd: string | null;
    indCustAbroadTaxpayerNumber: string | null;
    indCustAbroadDepartureNoticeDate: string | null;
    indCustAbroadInitialDateAbroad: string | null;
    indCustAbroadFinalDateAbroad: string | null;
    indCustAbroadICV560Qualification: string | null;
    indCustAbroadICV560QualificationDscn: string | null;
    indCustAbroadInternationalJurisdictionCode: string | null;
    indCustAbroadInternationalJurisdictionName: string | null;
    indCustAbroadLegalRepresentTypePsonCode: string;
    indCustAbroadLegalRepresentDocmValue: string;
    indCustAbroadLegalRepresentName: string;
  };
  individualCustFinan: {
    indCustFinCurrencyCode: number;
    indCustFinCurrencyName: string;
    indCustFinAnnualIncomeValue: number;
    indCustFinAnnualIncomeDate: string;
    indCustFinFinancialValue: number;
    indCustFinFinancialDate: string;
    indCustFinCapacityValue: number;
    indCustFinCapacityDate: string;
  };
  legalEntity: {
    legEntFoundDate: string | null;
    legEntCountryAcrn: string;
    legEntCountryName: string | null;
    legEntEconomicActvCode: string;
    legEntEconomicActvName: string | null;
    legEntEconomicGroupName: string;
    legEntLegalNatureCode: number | null;
    legEntCVM286Ind: string;
    legEntOrdersByThirdParties: string;
    legEntManagedPortfolioAdmin: string;
    legEntInvestFundManager: string;
    legEntRiskClassificationInd: number | null;
    legEntRiskClassificationDscn: string;
    legEntNonprofitCompany: string;
  };
  legalEntityAbroad: {
    legEntAbroadInternationalJurisdictionCode: string | null;
    legEntAbroadInternationalJurisdictionName: string | null;
    legEntAbroadAccOwnershipType: string | null;
    legEntAbroadTaxpayerIdInd: string | null;
    legEntAbroadTaxpayerIdNumber: string | null;
    legEntAbroadBearerShareCompany: string;
    legEntAbroadExclusiveInvestmentFund: string;
  };
  legalEntityFinancial: {
    legEntFinCurrencyCode: number | null;
    legEntFinCurrencyName: string | null;
    legEntFinNetWorthValue: number | null;
    legEntFinNetWorthDate: string | null;
    legEntFinCapacityValue: number | null;
    legEntFinCapacityDate: string | null;
    legEntFinAverageMonthlyRevenue: number | null;
    legEntFinAverageMonthlyDate: string | null;
  };
  shareLegalEntity: {
    shareLegEntShareholderName: string;
    shareLegEntShareholderPepInd: string;
  };
  account: {
    accTypeAccCode: number;
    accTypeAccName: string;
    accRuleMovAcrn: string;
    accTypeCollateralCode: string;
    accAffinityCode: number;
    accStatRegCode: number;
    accStatRegDscn: string;
    accSendAccBvmfInd: string;
  }[];
  document: {
    docDocmValue: string;
    docCustMainDocm: string;
    docDocmTypeCode: number;
    docDocmTypeName: string;
    docDomainBvmfInd: string;
    docIssuingAgencyCode: number;
    docIssuingAgencyAcrn: string;
    docCountryAcrn: string;
    docCountryName: string;
    docStateAcrn: string;
    docStateName: string;
    docMainDocm: string;
    docIssuanceDate: string;
    docExpirationDate: string;
  }[];
  address: {
    addAddressPurposeCode: number;
    addAddressPurposeName: string;
    addAddressTypeCode: number;
    addAddressTypeName: string;
    addStreetName: string;
    addStreetNumber: string;
    addAdditionalAddressText: string;
    addNeighborhoodName: string;
    addZipCodeNumber: number;
    addZipCodeExtension: number;
    addCountryAcrn: string;
    addCountryName: string;
    addStateAcrn: string;
    addStateName: string;
    addCityName: string;
    addOfficialAddressInd: string;
    addResponsiblePson: string;
    addSendBvmfInd: string;
    addMunicipalityCode: number;
    addMunicipalityName: string;
    addAddressCode: number;
    addAddressPurposeBvmfCode: number;
    addForeignZipCode: string | null;
    addForeignStateName: string;
  }[];
  phone: {
    phoneDeviceTypeCode: string;
    phoneDeviceTypeName: string;
    phoneDdiCode: number;
    phoneDddCode: number;
    phoneNumber: string;
    phoneExtensionPhoneNumber: number | null;
    phoneContactPsonName: string;
    phoneCode: number;
    phoneBvmfCode: number | null;
    phonePurposeCode: number;
    phonePurposeDscn: string;
  }[];
  email: {
    emailAddress: string;
    emailCode: number;
    emailBvmfCode: number | null;
    emailPurposeCode: number;
    emailPurposeName: string;
  }[];
  personRelationshipCus: {
    relatCusPsonRelationshipCode: number;
    relatCusDocumentCode: string;
    relatCusRelationshipTypeCode: number;
    relatCusRelationshipTypeName: string;
    relatCusParticipationPercentageNumber: number;
    relatCusBeginDate: string;
    relatCusEndDate: string | null;
    relatCusSendBvmfInd: string;
  }[];
}